# Generated by Django 4.1.13 on 2024-08-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenurl',
            name='full_url',
            field=models.URLField(),
        ),
    ]
