# Generated by Django 4.1.13 on 2024-08-20 05:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_tokenurl_full_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tokenurl',
            unique_together={('full_url', 'owner')},
        ),
    ]
